// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_XlK-MxoIMHuzUN3qhU86G8CUr-swsM',
    appId: '1:247172018141:web:0ccdb3b0a1adfdb17e1034',
    messagingSenderId: '247172018141',
    projectId: 'organizerapp-163c4',
    authDomain: 'organizerapp-163c4.firebaseapp.com',
    storageBucket: 'organizerapp-163c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1pn3mUOgAE6B74I0PRyFRZUfmfJmdws',
    appId: '1:247172018141:android:f07347fc90a9cb867e1034',
    messagingSenderId: '247172018141',
    projectId: 'organizerapp-163c4',
    storageBucket: 'organizerapp-163c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD14SYyNjZkwg3Xvk8tLV5uKp0eQ9moDbE',
    appId: '1:247172018141:ios:4dbb975d225315a67e1034',
    messagingSenderId: '247172018141',
    projectId: 'organizerapp-163c4',
    storageBucket: 'organizerapp-163c4.appspot.com',
    iosClientId: '247172018141-m0u3i5eg2rlr603aakl4q01fqaphv8c9.apps.googleusercontent.com',
    iosBundleId: 'de.organizerapp.androidProgOrganizerApp',
  );
}
